version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-beaverhabits_app_1
      APP_PORT: 8080

  app:
    image: daya0576/beaverhabits:0.6.2@sha256:37ae5a2fc310dce707a10f44234d9648eb62dea978d51cd5311d46d1e51ec964
    restart: unless-stopped
    user: 1000:1000
    environment:
      - HABITS_STORAGE=USER_DISK
      - FIRST_DAY_OF_WEEK=0
      - MAX_USER_COUNT=1
      - ENABLE_IOS_STANDALONE=true
      - INDEX_HABIT_DATE_COLUMNS=5
      - INDEX_HABIT_DATE_REVERSE=true
      - DARK_MODE=true
    volumes:
      - ${APP_DATA_DIR}/data:/app/.user/
