version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-reubah_app_1
      APP_PORT: 8081

  app:
    image: ghcr.io/dendianugerah/reubah:sha-4d0a141@sha256:02dfe7d3fe9d1c32ca2dbe8c7acee8fc743c6e872f60fa71d1a9d5a1887b780d
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: on-failure
